# Voxtral Agentic Voice Platform Configuration v1.0.0

vllm_endpoint: "http://localhost:8000/v1"
model_name: "mistralai/Voxtral-Mini-3B-2507"

voice:
  sample_rate: 16000
  chunk_size: 1024
  channels: 1
  hush_word: "__stop__"
  silence_threshold: 0.01
  silence_duration: 2.0
  push_to_talk: false
  continuous_mode: true

model:
  temperature_transcription: 0.0
  temperature_chat: 0.2
  top_p: 0.95
  max_tokens: 2048
  gpu_memory_utilization: 0.8
  tensor_parallel_size: 1
  enable_tool_use: true
  tokenizer_mode: "mistral"
  config_format: "mistral"
  load_format: "mistral"

system:
  os_type: "linux"
  desktop_environment: "gnome"
  display_server: "wayland"
  audio_backend: "pulseaudio"
  cursor_injection: true
  restart_services:
    - "pulseaudio"
    - "pipewire"
    - "seatd"
  logout_required: false

tool_list:
  - name: run_shell
    description: "Run safe shell commands"
  - name: search_web
    description: "Search web with DuckDuckGo API"
  - name: open_url
    description: "Open webpage in default browser"
  - name: type_text
    description: "Type text at cursor position"

tray_theme: "dark"
auto_start_agent: true
debug: false
log_level: "INFO"

# Global hotkeys
hotkeys:
  activation_keys: ["ctrl", "alt"]
  enabled: true
  toggle_mode: true  # true = toggle, false = push-to-talk
  feedback:
    type: "visual"  # "visual", "audio", "both", "none"
    visual: true
    audio: false
    notification: true

# Service management
service:
  preferred_startup_method: "systemd"  # "systemd", "desktop", "manual"
  check_duplicates: true
  auto_restart: true
  restart_delay: 5

# Enhanced cursor typing
cursor_typing:
  detection_method: "auto"  # "auto", "window_focus", "clipboard_only"
  fallback_to_clipboard: true
  typing_delay: 0.05
  window_detection_timeout: 2.0
  preferred_apps: ["code", "gedit", "kate", "sublime"]

# Enhanced Whisper configuration
whisper:
  model_size: "base"  # "tiny", "base", "small", "medium", "large", "large-v2", "large-v3"
  language: null  # Auto-detect language, or specify like "en", "ar", "es"
  task: "transcribe"  # "transcribe" or "translate"
  temperature: 0.0  # 0.0 = deterministic, higher = more creative
  word_timestamps: false  # Enable word-level timestamps (requires WhisperX)
  verbose: false  # Debug output
  
  # Performance settings
  fp16: true  # Use half precision (faster on GPU)
  best_of: 1  # Number of candidates to consider
  beam_size: 5  # Beam search width
  
  # Quality filters
  compression_ratio_threshold: 2.4  # Filter repetitive text
  logprob_threshold: -1.0  # Filter low-confidence segments
  no_speech_threshold: 0.6  # Filter silence segments
  
  # Real-time settings
  chunk_duration: 3.0  # Seconds per processing chunk
  silence_threshold: 0.01  # RMS energy threshold for silence detection
  min_recording_duration: 0.8  # Minimum recording length to process